# Generated by Django 6.0.2 on 2026-02-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
